In [2]:
from urllib.request import urlopen as request
import json
import numpy as np
import time

request_url = "https://api.opendota.com/api/publicMatches"

class sklearn_dataset:
    def __init__(self, data_array, target_array):
        self.data = np.array(data_array)
        self.target = np.array(target_array)

def mine_data(count=1000, timeout=15):
    matches = []
    less_than_match_id = -1
    less_than_match_str = ""
    while len(matches) < count:
        try:
            response = request(request_url + less_than_match_str, timeout=timeout)
        except:
            print("Failed to make a request starting at match ID: ", less_than_match_id)
            time.sleep(timeout)
            less_than_match_id -= 1
        else:
            response_json = json.load(response)
            less_than_match_id = response_json[-1]['match_id']
            less_than_match_str = "?less_than_match_id=" + str(less_than_match_id)
            matches.extend(response_json)
            print(len(matches), end=' ')
    return matches

def save_original_data(matches, file_name='origin.txt'):
    with open(file_name, 'w') as f:
        for match in matches:
            f.write(json.dumps(match) + '\n')

In [23]:
matches = mine_data(count=500000)
save_original_data(matches)


100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200 10300 10400 10500 10600 10700 10800 10900 11000 11100 11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200 12300 12400 12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800 14900 15000 15100 15200 15300 15400 15500 15600 15700 15800 15900 16000 16100 16200 16300 16400 16500 16600 16700 16800 16900 17000 17100 17200 17300 17400 17500 17600 17700 17800 17900 18000 18100 18200 18300 18400 1850

244100 244200 244300 244400 244500 244600 244700 244800 244900 245000 245100 245200 245300 245400 245500 245600 245700 245800 245900 246000 246100 246200 246300 246400 246500 246600 246700 246800 246900 247000 247100 247200 247300 247400 247500 247600 247700 247800 247900 248000 248100 248200 248300 248400 248500 248600 248700 248800 248900 249000 249100 249200 249300 249400 249500 249600 249700 249800 249900 250000 250100 250200 250300 250400 250500 250600 250700 250800 250900 251000 251100 251200 251300 251400 251500 251600 251700 251800 251900 252000 252100 252200 252300 252400 252500 252600 252700 252800 252900 253000 253100 253200 253300 253400 253500 253600 253700 253800 253900 254000 254100 254200 254300 254400 254500 254600 254700 254800 254900 255000 255100 255200 255300 255400 255500 255600 255700 255800 255900 256000 256100 256200 256300 256400 256500 256600 256700 256800 256900 257000 257100 257200 257300 257400 257500 257600 257700 257800 257900 258000 258100 258200 258300

361200 361300 361400 361500 361600 361700 361800 361900 362000 362100 362200 362300 362400 362500 362600 362700 362800 362900 363000 363100 363200 363300 363400 363500 363600 363700 363800 363900 364000 364100 364200 364300 364400 364500 364600 364700 364800 364900 365000 365100 365200 365300 365400 365500 365600 365700 365800 365900 366000 366100 366200 366300 366400 366500 366600 366700 366800 366900 367000 367100 367200 367300 367400 367500 367600 367700 367800 367900 368000 368100 368200 368300 368400 368500 368600 368700 368800 368900 369000 369100 369200 369300 369400 369500 369600 369700 369800 369900 370000 370100 370200 370300 370400 370500 370600 370700 370800 370900 371000 371100 371200 371300 371400 371500 371600 371700 371800 371900 372000 372100 372200 372300 372400 372500 372600 372700 372800 372900 373000 373100 373200 373300 373400 373500 373600 373700 373800 373900 374000 374100 374200 374300 374400 374500 374600 374700 374800 374900 375000 375100 375200 375300 375400

In [1]:
import requests
from lxml import html

page = requests.get('http://www.dotamax.com/hero/cs/')
tree = html.fromstring(page.text)
a = tree.xpath('//table/tbody/tr//span/text()')
b = tree.xpath('//table/tbody/tr/td[2]/div[1]/text()')
lh_per_10_mins = {a[i]: float(b[i]) for i in range(len(a))}
#print(lh_per_10_mins)
heroes = {}

with open('heroid.txt', 'r', encoding='utf8') as f:
    for line in f.readlines():
        matching = line.strip().split(',')
        lh_per_10_mins[matching[0]] = lh_per_10_mins.pop(matching[1])

print(lh_per_10_mins, print(heroes))

{'1': 73.33, '2': 35.73, '3': 13.14, '4': 43.47, '5': 14.56, '6': 42.01, '7': 22.17, '8': 53.42, '9': 34.25, '11': 58.68, '10': 48.47, '12': 44.87, '13': 37.68, '14': 14.51, '15': 39.93, '16': 28.45, '17': 46.67, '18': 51.3, '19': 37.37, '20': 22.58, '21': 33.92, '22': 29.11, '23': 37.25, '25': 36.45, '31': 14.95, '26': 11.01, '27': 19.85, '28': 21.98, '29': 26.88, '30': 13.18, '32': 15.24, '33': 38.34, '34': 46.86, '35': 47.57, '36': 31.63, '37': 19.96, '38': 33.5, '39': 39.34, '40': 34.12, '41': 48.49, '42': 44.89, '43': 32.08, '44': 42.92, '45': 28.15, '46': 45.71, '47': 35.7, '48': 59.68, '49': 40.15, '50': 14.57, '51': 20.42, '52': 31.77, '53': 51.65, '54': 40.09, '55': 34.76, '56': 29.82, '57': 23.02, '58': 28.25, '59': 28.43, '60': 24.45, '61': 38.39, '62': 15.28, '63': 36.6, '64': 19.71, '65': 22.95, '66': 21.74, '67': 48.09, '69': 33.31, '68': 12.51, '70': 32.01, '71': 16.38, '72': 46.27, '73': 56.91, '74': 41.61, '75': 22.1, '76': 40.4, '77': 39.14, '78': 36.16, '79': 16.3, '

In [171]:
def load_original_data(file_name='origin.txt'):
    matches = []
    with open(file_name, 'r') as f:
        for line in f.readlines():
            json_str = line.strip()
            matches.append(json.loads(json_str))
    return matches

In [172]:
def process_data(matches, duration_min=0, duration_max=3600, mmr_min=0, mmr_max=10000):
    teams_win = []
    matches_heroes = []
    for match in matches:
        duration = match['duration']
        mmr = match['avg_mmr']
        if isinstance(duration, int) is False or isinstance(mmr, int) is False:
            continue
        if duration < duration_min or duration > duration_max:
            continue
        if mmr > mmr_max or mmr < mmr_min or match['lobby_type'] is not 7:
            continue
        match_heroes = [0 for i in range(120)]
        #match_heroes2 = [0 for i in range(120)]
        radiant_team = match['radiant_team'].split(',')
        dire_team = match['dire_team'].split(',')
        if match['radiant_win']:
            team_win = 1
        else:
            team_win = 0
        if len(radiant_team) is not 5 or len(dire_team) is not 5:
            continue
        for hero_id in radiant_team:
            match_heroes[int(hero_id)-1] = 1
            #match_heroes2[int(hero_id)-1] = -1
        for hero_id in dire_team:
            match_heroes[int(hero_id)-1] = -1
            #match_heroes2[int(hero_id)-1] = 1
        teams_win.append(team_win)
        matches_heroes.append(match_heroes)
        #teams_win.append(-team_win)
        #matches_heroes.append(match_heroes2)
    return sklearn_dataset(matches_heroes, teams_win)

In [173]:
import json
from sklearn import metrics
from sklearn.model_selection import train_test_split
matches = load_original_data(file_name='origin.txt')

In [174]:
matches_train, matches_test = train_test_split(matches, test_size=0.2)
matches_data_train = process_data(matches_train, duration_max=1800)
matches_data_test = process_data(matches_test, duration_max=1800)
xM, xT, yM, yT = matches_data_train.data, matches_data_test.data, matches_data_train.target, matches_data_test.target
xM.shape, xT.shape, yM.shape, yT.shape

((38412, 120), (9502, 120), (38412,), (9502,))

In [175]:
from sklearn.linear_model import LogisticRegression as CLF
cls = CLF(n_jobs=-1).fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'lr.model')

['lr.model']

In [176]:
from sklearn.externals import joblib
from sklearn.linear_model import LogisticRegression as CLF
cls = joblib.load('lr.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[2047, 1567],
        [ 915, 4973]]), 0.738791833298253)

In [177]:
res_p = cls.predict_proba(xT)
res_f = []
PROBA = 0.55
for proba in res_p:
    if proba[0] > PROBA:
        res_f.append(1)
    elif proba[1] > PROBA:
        res_f.append(-1)
len(res_f), len(res_p)

(8517, 9502)

In [31]:
def process_data(matches, duration_min=0, duration_max=3600, mmr_min=0, mmr_max=10000):
    teams_win = []
    matches_heroes = []
    cnt = 0
    for match in matches:
        if cnt >= 500000:
            break
        duration = match['duration']
        mmr = match['avg_mmr']
        if isinstance(duration, int) is False or isinstance(mmr, int) is False:
            continue
        if duration < duration_min or duration > duration_max:
            continue
        if mmr > mmr_max or mmr < mmr_min or match['lobby_type'] is not 7:
            continue
        match_heroes = [0 for i in range(120)]
        match_heroes2 = [0 for i in range(120)]
        radiant_team = match['radiant_team'].split(',')
        dire_team = match['dire_team'].split(',')
        if match['radiant_win']:
            team_win = 1
        else:
            team_win = 0
        if len(radiant_team) is not 5 or len(dire_team) is not 5:
            continue
        for hero_id in radiant_team:
            match_heroes[int(hero_id)-1] = 1
            match_heroes2[int(hero_id)-1] = -1
        for hero_id in dire_team:
            match_heroes[int(hero_id)-1] = -1
            match_heroes2[int(hero_id)-1] = 1
        teams_win.append(team_win)
        matches_heroes.append(match_heroes)
        #teams_win.append(1-team_win)
        #matches_heroes.append(match_heroes2)
        cnt += 1
    return sklearn_dataset(matches_heroes, teams_win)
matches_train, matches_test = train_test_split(matches, test_size=0.2)
matches_data_train = process_data(matches_train, duration_max=7200, duration_min=3300)
matches_data_test = process_data(matches_test, duration_max=7200, duration_min=3300)
xM, xT, yM, yT = matches_data_train.data, matches_data_test.data, matches_data_train.target, matches_data_test.target
print(xM.shape, xT.shape, yM.shape, yT.shape)
from sklearn import naive_bayes
cls = naive_bayes.GaussianNB()
cls.fit(xM, yM)
res = cls.predict(xT)
print(metrics.accuracy_score(yT, res))
from sklearn.linear_model import LogisticRegression as CLF
cls = CLF(n_jobs=-1).fit(xM, yM)
cls.fit(xM, yM)
res = cls.predict(xT)
print(metrics.accuracy_score(yT, res))

(25946, 120) (6474, 120) (25946,) (6474,)
0.5118937287611987
0.5675007723200495


In [49]:
# slow
from sklearn.svm import LinearSVC as CLF
cls = CLF().fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'svc.model')
res = cls.predict(xT)
print(metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res))

[[40683 28424]
 [28424 40683]] 0.5886957905856136


In [43]:
# fast
from sklearn.ensemble import RandomForestClassifier as CLF
cls = CLF().fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'rf.model')
res = cls.predict(xT)
print(metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res))

[[44865 24242]
 [39276 29831]] 0.5404372928936287


In [44]:
# fast
from sklearn import naive_bayes
cls = naive_bayes.GaussianNB()
cls.fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'nb.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[40615, 28492],
        [28492, 40615]]), 0.5877118092233783)

In [48]:
from sklearn.linear_model import Perceptron as CLF
cls = CLF().fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'perceptron.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[43097, 26010],
        [39470, 29637]]), 0.5262419147119684)

In [45]:
# fast
from sklearn.tree import DecisionTreeClassifier as CLF
cls = CLF().fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'dt.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[35771, 33336],
        [33422, 35685]]), 0.516995383969786)

In [47]:
# slow
from sklearn.ensemble import AdaBoostClassifier as CLF
cls = CLF().fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'ab.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[39926, 29181],
        [30228, 38879]]), 0.5701665533158725)

In [46]:
# fast
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier as CLF
est = DecisionTreeClassifier()
cls = CLF(base_estimator=est).fit(xM, yM)
from sklearn.externals import joblib
joblib.dump(cls, 'abdt.model')
res = cls.predict(xT)
metrics.confusion_matrix(yT, res),metrics.accuracy_score(yT, res)

(array([[35648, 33459],
        [33072, 36035]]), 0.5186377646258701)

In [460]:
def process_data2(matches, count=1000):
    teams_win2 = []
    matches_heroes2 = []
    for match in matches:
        if match['duration'] > 1500:
            continue
        radiant_team = match['radiant_team'].split(',')
        dire_team = match['dire_team'].split(',')
        choose = []
        choose2 = []
        for hero_id in radiant_team:
            choose.append(int(hero_id))
        for hero_id in dire_team:
            choose.append(int(hero_id))
            choose2.append(int(hero_id))
        for hero_id in radiant_team:
            choose2.append(int(hero_id))
        if len(choose) is not 10 or len(choose2) is not 10:
            print(choose, choose2)
            continue
        if match['radiant_win']:
            team_win2 = 1
        else:
            team_win2 = -1
        teams_win2.append(team_win2)
        matches_heroes2.append(choose)
        teams_win2.append(-team_win2)
        matches_heroes2.append(choose2)
    return sklearn_dataset(matches_heroes2, teams_win2)

In [461]:
matches = load_original_data()
matches_data2 = process_data2(matches)
print(matches_data2.data.shape)
print(matches_data2.data[0])

from collections import defaultdict
cc = defaultdict(int)
for t in matches_data2.target:
    cc[t] += 1
print(cc)

(16878, 10)
[ 64  97 104  93  51  82  14   1  42  35]
defaultdict(<class 'int'>, {-1: 8439, 1: 8439})


In [462]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
xM2, xT2, yM2, yT2 = train_test_split(matches_data2.data, matches_data2.target, test_size=0.2)

In [463]:
from sklearn.ensemble import RandomForestClassifier as CLF
cls = CLF().fit(xM2, yM2)
res = cls.predict(xT2)
print(metrics.confusion_matrix(yT2, res),metrics.accuracy_score(yT2, res))

[[1164  574]
 [ 886  752]] 0.567535545024


In [464]:
from sklearn.linear_model import LogisticRegression as CLF
cls = CLF().fit(xM2, yM2)
res = cls.predict(xT2)
metrics.confusion_matrix(yT2, res),metrics.accuracy_score(yT2, res)

(array([[790, 948],
        [712, 926]]), 0.50829383886255919)

In [465]:
from sklearn import naive_bayes
cls = naive_bayes.GaussianNB()
cls.fit(xM2, yM2)
res = cls.predict(xT2)
metrics.confusion_matrix(yT2, res),metrics.accuracy_score(yT2, res)

(array([[879, 859],
        [686, 952]]), 0.54235781990521326)

In [466]:
from sklearn.ensemble import AdaBoostClassifier as CLF
cls = CLF().fit(xM2, yM2)
res = cls.predict(xT2)
metrics.confusion_matrix(yT2, res),metrics.accuracy_score(yT2, res)

(array([[1059,  679],
        [ 637, 1001]]), 0.6101895734597157)

C:\Users\Elinia\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [131]:
class sklearn_dataset:
    def __init__(self, data_array, target_array):
        self.data = np.array(data_array)
        self.target = np.array(target_array)

def load_original_data(file_name='origin.txt'):
    matches = []
    with open(file_name, 'r') as f:
        for line in f.readlines():
            json_str = line.strip()
            matches.append(json.loads(json_str))
    return matches

def process_data(matches, duration_min=0, duration_max=3600, mmr_min=0, mmr_max=10000):
    teams_win = []
    matches_heroes = []
    for match in matches:
        duration = match['duration']
        mmr = match['avg_mmr']
        if isinstance(duration, int) is False or isinstance(mmr, int) is False:
            continue
        if duration < duration_min or duration > duration_max:
            continue
        if mmr > mmr_max or mmr < mmr_min or match['lobby_type'] is not 7:
            continue
        match_heroes = [0 for i in range(120)]
        radiant_team = match['radiant_team'].split(',')
        dire_team = match['dire_team'].split(',')
        if match['radiant_win']:
            team_win = 1
        else:
            team_win = 0
        if len(radiant_team) is not 5 or len(dire_team) is not 5:
            continue
        for hero_id in radiant_team:
            match_heroes[int(hero_id)-1] = 1
        for hero_id in dire_team:
            match_heroes[int(hero_id)-1] = -1
        teams_win.append(team_win)
        matches_heroes.append(match_heroes)
    return sklearn_dataset(matches_heroes, teams_win)

import json
from sklearn import metrics
from sklearn.model_selection import train_test_split
matches = load_original_data(file_name='origin.txt')

matches_train, matches_test = train_test_split(matches, test_size=0.2)
matches_data_train = process_data(matches_train)
matches_data_test = process_data(matches_test)

In [132]:
xM, xT, yM, yT = matches_data_train.data, matches_data_test.data, matches_data_train.target, matches_data_test.target
print(xM.shape, xT.shape, yM.shape, yT.shape)
from sklearn.linear_model import LogisticRegression as CLF
cls = CLF(n_jobs=-1).fit(xM, yM)
cls.fit(xM, yM)
res = cls.predict(xT)
print(metrics.accuracy_score(yT, res))
res_p = cls.predict_proba(xT)

(276059, 120) (69061, 120) (276059,) (69061,)
0.587335833538466


In [133]:
import numpy as np
import gzip
import struct
import matplotlib.pyplot as plt
import mxnet as mx
import logging

def to4d(img):
    print(img.shape)
    return img.reshape(img.shape[0], 1, 1, 120)

batch_size = 100
#print(matches_data_train.data[0])
#print(to4d(matches_data_train.data)[0])
train_iter = mx.io.NDArrayIter(to4d(matches_data_train.data), matches_data_train.target, batch_size, shuffle=True)
val_iter = mx.io.NDArrayIter(to4d(matches_data_test.data), matches_data_test.target, batch_size)

# Create a place holder variable for the input data
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data=data, num_hidden=120)
act1 = mx.symbol.Activation(data=fc1, act_type="relu")
fc2 = mx.symbol.FullyConnected(data=act1, num_hidden=120)
act2 = mx.symbol.Activation(data=fc2, act_type="relu")
fc3 = mx.symbol.FullyConnected(data=data, num_hidden=120)
act3 = mx.symbol.Activation(data=fc2, act_type="relu")
fc4 = mx.symbol.FullyConnected(data=act3, num_hidden=120)
act4 = mx.symbol.Activation(data=fc3, act_type="relu")
fcn = mx.symbol.FullyConnected(data=act4, num_hidden=2)
mlp = mx.symbol.SoftmaxOutput(data=fcn, name='softmax')

# Output may vary
logging.getLogger().setLevel(logging.DEBUG)

model = mx.mod.Module(mlp)
model.fit(
    train_iter,       # training data
    num_epoch=3
)
print("finished")

(276059, 120)
(69061, 120)


INFO:root:Epoch[0] Train-accuracy=0.527465
INFO:root:Epoch[0] Time cost=1.579
INFO:root:Epoch[1] Train-accuracy=0.527490
INFO:root:Epoch[1] Time cost=1.535
INFO:root:Epoch[2] Train-accuracy=0.537751
INFO:root:Epoch[2] Time cost=1.675


finished


In [134]:
model2 = mx.model.FeedForward(
    symbol=mlp,       # network structure
    num_epoch=5,     # number of data passes for training
    learning_rate=0.2 # learning rate of SGD
)
model2.fit(
    X=train_iter,       # training data
    eval_data=val_iter, # validation data
    batch_end_callback=mx.callback.Speedometer(batch_size, 100) # output progress for each 200 data batches
)
prob_array = model2.predict(val_iter)
prob = prob_array[0]
print(prob)

C:\Users\Elinia\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  after removing the cwd from sys.path.
C:\Users\Elinia\Anaconda3\lib\site-packages\mxnet\model.py:573: DeprecationWarning: Calling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.
  self.initializer(k, v)
INFO:root:Start training with [cpu(0)]
INFO:root:Epoch[0] Batch [100]	Speed: 144819.94 samples/sec	accuracy=0.526200
INFO:root:Epoch[0] Batch [200]	Speed: 147449.49 samples/sec	accuracy=0.532300
INFO:root:Epoch[0] Batch [300]	Speed: 126477.32 samples/sec	accuracy=0.528500
INFO:root:Epoch[0] Batch [400]	Speed: 123617.12 samples/sec	accuracy=0.536100
INFO:root:Epoch[0] Batch [500]	Speed: 157356.42 samples/sec	accuracy=0.566200
INFO:root:Epoch[0] Batch [600]	Speed: 162479.87 samples/sec	accuracy=0.570700
INFO:root:Epoch[0] Batch [700]	Speed: 166535.80 samp

INFO:root:Epoch[3] Batch [1400]	Speed: 158619.20 samples/sec	accuracy=0.580800
INFO:root:Epoch[3] Batch [1500]	Speed: 167931.36 samples/sec	accuracy=0.585900
INFO:root:Epoch[3] Batch [1600]	Speed: 153724.79 samples/sec	accuracy=0.585100
INFO:root:Epoch[3] Batch [1700]	Speed: 131487.42 samples/sec	accuracy=0.587300
INFO:root:Epoch[3] Batch [1800]	Speed: 165163.24 samples/sec	accuracy=0.584400
INFO:root:Epoch[3] Batch [1900]	Speed: 172272.61 samples/sec	accuracy=0.583300
INFO:root:Epoch[3] Batch [2000]	Speed: 166547.70 samples/sec	accuracy=0.581100
INFO:root:Epoch[3] Batch [2100]	Speed: 172301.63 samples/sec	accuracy=0.589500
INFO:root:Epoch[3] Batch [2200]	Speed: 175315.64 samples/sec	accuracy=0.589900
INFO:root:Epoch[3] Batch [2300]	Speed: 158600.00 samples/sec	accuracy=0.589400
INFO:root:Epoch[3] Batch [2400]	Speed: 166539.10 samples/sec	accuracy=0.588700
INFO:root:Epoch[3] Batch [2500]	Speed: 175316.37 samples/sec	accuracy=0.586400
INFO:root:Epoch[3] Batch [2600]	Speed: 156126.96 sam

[0.612761   0.38723895]


In [138]:
# Output may vary
prob_array = model2.predict(val_iter)

print(prob_array[:20])
#print(matches_data_test.data[:10])
print(matches_data_test.target[:20])
#print('Classified as %d with probability %f' % (prob.argmax(), max(prob)))

[[0.612761   0.38723895]
 [0.43503264 0.56496733]
 [0.5823029  0.41769704]
 [0.40150955 0.5984904 ]
 [0.5329015  0.46709844]
 [0.6076546  0.3923455 ]
 [0.6061671  0.3938329 ]
 [0.476143   0.523857  ]
 [0.5569738  0.44302616]
 [0.53853226 0.46146774]
 [0.37281102 0.62718904]
 [0.45460212 0.5453979 ]
 [0.47830838 0.5216916 ]
 [0.3763013  0.6236987 ]
 [0.5018194  0.4981807 ]
 [0.668009   0.331991  ]
 [0.38347962 0.61652035]
 [0.5137781  0.4862219 ]
 [0.56783813 0.43216187]
 [0.45609206 0.54390794]]
[0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 0 1]


In [139]:
res_p[:20]

array([[0.58425885, 0.41574115],
       [0.42965535, 0.57034465],
       [0.56894204, 0.43105796],
       [0.38722292, 0.61277708],
       [0.50190872, 0.49809128],
       [0.62193167, 0.37806833],
       [0.59057048, 0.40942952],
       [0.48057085, 0.51942915],
       [0.5577027 , 0.4422973 ],
       [0.51251977, 0.48748023],
       [0.3453744 , 0.6546256 ],
       [0.43659067, 0.56340933],
       [0.47628933, 0.52371067],
       [0.40518889, 0.59481111],
       [0.50895706, 0.49104294],
       [0.67994457, 0.32005543],
       [0.37004582, 0.62995418],
       [0.48779835, 0.51220165],
       [0.54220318, 0.45779682],
       [0.48193102, 0.51806898]])

In [140]:
count = 0
very_count = 0
very_wrong = 0
very_right = 0
rate = 0.60
for i in range(prob_array.shape[0]):
    count += 1
    if matches_data_test.target[i] == 0:
        if prob_array[i][0] < 1-rate:
            very_count += 1
            very_wrong += 1
        elif prob_array[i][0] > rate:
            very_count += 1
            very_right += 1
    elif matches_data_test.target[i] == 1:
        if prob_array[i][1] < 1-rate:
            very_count += 1
            very_wrong += 1
        elif prob_array[i][1] > rate:
            very_count += 1
            very_right += 1
print(count, very_count, very_wrong, very_right, very_right/(very_right+very_wrong))

69061 26129 9105 17024 0.6515366068353171
